# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExpressNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExpressNews
	pod 'PromiseKit'
  pod 'SDWebImage'
  pod 'ANActivityIndicator'

  target 'ExpressNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExpressNewsUITests' do
    # Pods for testing
  end

end
